/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    JoAccordeon: typeof import('./src/components/JoAccordeon.vue')['default']
    JoBerlinTimer: typeof import('./src/components/JoBerlinTimer.vue')['default']
    JoCursor: typeof import('./src/components/JoCursor.vue')['default']
    JoHeroHeading: typeof import('./src/components/JoHeroHeading.vue')['default']
    JoImprint: typeof import('./src/components/JoImprint/JoImprint.vue')['default']
    JoImprintContent: typeof import('./src/components/JoImprint/JoImprintContent.vue')['default']
    JoImprintPrivacy: typeof import('./src/components/JoImprint/JoImprintPrivacy.vue')['default']
    JoNavigation: typeof import('./src/components/navigation/JoNavigation.vue')['default']
    NavigationItem: typeof import('./src/components/navigation/NavigationItem.vue')['default']
    SectionAbout: typeof import('./src/components/section/SectionAbout.vue')['default']
    SectionContact: typeof import('./src/components/section/SectionContact.vue')['default']
    SectionFooter: typeof import('./src/components/section/SectionFooter.vue')['default']
    SectionHero: typeof import('./src/components/section/SectionHero.vue')['default']
    SectionProjects: typeof import('./src/components/section/SectionProjects.vue')['default']
  }
}
